export enum CCIPMessageType {
    DEPOSIT,
    DEPOSIT_COLLATERAL,
    WITHDRAW,
    WITHDRAW_COLLATERAL,
    BORROW,
    CREATE_REQUEST,
    SERVICE_REQUEST,
    CREATE_LISTING,
    BORROW_FROM_LISTING,
    REPAY,
    REPAY_LOAN,
    CLOSE_LISTING_AD,
    CLOSE_REQUEST
  }